# Generated by Django 4.0.3 on 2022-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('genere', models.CharField(choices=[('Action', 'Action'), ('Classics', 'Classics'), ('Comic', 'Comic'), ('Detective', 'Detective'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('LF', 'Literary Fiction')], default='Action', max_length=50)),
                ('released_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
