# Generated by Django 4.0.3 on 2022-03-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genere',
            field=models.CharField(choices=[('Action', 'Action'), ('Classics', 'Classics'), ('Comic', 'Comic'), ('Detective', 'Detective'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('LF', 'Literary Fiction')], default='Action', max_length=255),
        ),
    ]
